### PR TITLE
All API functionality for Sprint 9 and submission for review

### PR DESCRIPTION
**Pull request by Wylerlight**
## What was completed:

- API Functionality for changing avatar profile picture
- API Functionality for confirming card delete
- API Functionality for adding/removing likes
- API Functionality for pulling and displaying user data
- API Functionality for pulling card data and rendering
- API Functionality for adding card data to list
- "Saving..." notification for form submissions

### CODE REVIEW

**Review by gennady-bars — COMMENTED** [review]
Dear Tyler , (**Please, expand the general comment ↓**)

Unfortunately I have to reject the project:



* See here https://disk.yandex.ru/i/K_vjVrRxJpodxg In **Files changed** there should be the code that should be reviewed. So, all changes from the last sprint should be there. But now you have only 1 file there. I'm not able to leave comments in your code. Please, try to send me a new pull request with all files changed

**Comment by Wylerlight** [comment]
I apologize. I pushed the changes to the main branch at first before creating the new branch. What should I do so that you can access all my Sprint 9 work?

**Comment by gennady-bars** [comment]
> What should I do so that you can access all my Sprint 9 work?

Hi)

You can make a new branch from main, then delete all code from **main**, commit it, push it and after that you need to make a pull request. So, in this request you'll have all files of the project (not only changed)

**Review by gennady-bars — COMMENTED** [review]
Dear Tyler , (**Please, expand the general comment ↓**)

Unfortunately I have to reject the project:



* See here https://disk.yandex.ru/i/K_vjVrRxJpodxg In **Files changed** there should be the code that should be reviewed. So, all changes from the last sprint should be there. But now you have only 1 file there. I'm not able to leave comments in your code. Please, try to send me a new pull request with all files changed

------------------


> What should I do so that you can access all my Sprint 9 work?

Hi)

You can make a new branch from main, then delete all code from **main**, commit it, push it and after that you need to make a pull request. So, in this request you'll have all files of the project (not only changed)

**Comment by Wylerlight** [comment]
I just submitted the main brain for review. If necessary, I'll attempt this option if the main branch will not work. I apologize for the inconvenience! 😅

**Pull request closed without merging**
